require_relative '../loader'

describe 'dev' do
  it 'expects to capture error' do
    response = GenericApi.render :about
    expect(response).to eq({ error: { code: 500, messages: ["Error happens"] }, meta: { ip: "1.2.3.4"}, success: false, status: 400 })
  end

  it 'gets error generated by code' do
    response = GenericApi.render :get_money
    expect(response).to eq({
      error: { code: 405, messages: ["$ not found"] },
      meta:  { ip: '1.2.3.4' },
      status: 400,
      success: false
    })
  end

  it 'can generete error in root' do
    err = GenericApi.response_error('foo bar').to_h
    expect(err[:error][:messages][0]).to eq('foo bar')
  end
end