source 'https://rubygems.org'

gem 'joshua', path: '../..'
gem 'sinatra'
gem 'rackup'
gem 'puma'

# joshua loads Sequel.extension :inflector for String#classify when no
# ActiveSupport / similar is present
gem 'sequel'

group :development do
  gem 'rerun' # file watcher; restarts puma on .rb changes
end
